import Head from 'next/head'
import Image from 'next/image'
import { useRef, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const inputRef = useRef(null)

  const [message, setMessage] = useState('')

  async function subscribe(e) {
    e.preventDefault()

    const res = await fetch('/api/subscribe', {
      body: JSON.stringify({
        email: inputRef.current.value
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    })

    const { error } = await res.json()

    if (error) {
      setMessage(error)

      console.log(error)
      return
    }

    inputRef.current.value = ''
    setMessage('Success!')



  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        

        <div className={styles.grid}>
          <form onSubmit={subscribe}>
            <label htmlFor='email-input'>Email Address</label>
            <input
              id="email-input"
              name="email"
              placeholder='you@awesome.com'
              ref={inputRef}
              required
              type="email"
            />
            <div>
              {message ? message : null}
            </div>
            <button type="submit">Subscribe</button>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
